
platform :ios, '8.0'
target:"Coding" do
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~>3.8'
pod 'YYModel'
pod 'MJRefresh'
pod 'TTTAttributedLabel'
end
